apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - image: docker.io/11098078/vote:6ecf222fcb6c94717f751d38f026272623b1f8a0
          name: vote-ui
          ports:
            - containerPort: 80
