apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - image: docker.io/11098078/vote:d43cf42589a84574bc04ee8c8b817d7693849acc
          name: vote-ui
          ports:
            - containerPort: 80
